SELECT
    EXTRACT(YEAR FROM booked_at AT TIME ZONE 'UTC') AS YEAR,
    EXTRACT(MONTH FROM booked_at AT TIME ZONE 'UTC') AS MONTH,
    EXTRACT(DAY FROM booked_at AT TIME ZONE 'UTC') AS DAY,
    EXTRACT(HOUR FROM booked_at AT TIME ZONE 'UTC') AS HOUR,
    EXTRACT(MINUTE FROM booked_at AT TIME ZONE 'UTC') AS MINUTE,
    CEILING(EXTRACT(SECOND FROM booked_at AT TIME ZONE 'UTC')) AS SECOND
FROM bookings;